### ISSUE TITLE
add collaborators to the repo

### ISSUE THREAD

**Issue by afred** [WGBH/AAPB-etc#1]
**done when** me, Kevin, et al have access

**Comment by mccalluc** [comment]
I've added https://github.com/orgs/WGBH/teams/wgbh-mla-devs with admin privs. ( @afred: There is no one else on that team... Should Mike be included in "et al"?)

**Comment by afred** [comment]
@mccalluc probably. My use of "et al" was an effort to avoid decision making.

**Comment by mccalluc** [comment]
just added him.
